--Which vehicle makes have sold the most vehicles in our auctions?

SELECT
    v.make,
    COUNT(*) AS total_vehicles_sold
FROM vehicles v
JOIN auction_sales a
    ON v.vehicle_id = a.vehicle_id
GROUP BY v.make
ORDER BY total_vehicles_sold DESC;

--What is the total revenue generated by each vehicle make?
--Write a query that returns: make, total_revenue

SELECT
    v.make,count(*) AS total_vehicles_sold,
    ROUND(SUM(a.selling_price), 2) AS total_revenue
FROM 

vehicles v
JOIN auction_sales a
    ON v.vehicle_id = a.vehicle_id
GROUP BY v.make
ORDER BY total_revenue DESC;

--Which vehicle make has the highest average selling price?
--Write a query that returns: make, average_selling_price

SELECT
    v.make,count(*) AS total_vehicles_sold,
    ROUND(avg(a.selling_price), 2) AS average_selling_price
FROM 

vehicles v
JOIN auction_sales a
    ON v.vehicle_id = a.vehicle_id
GROUP BY v.make
ORDER BY average_selling_price DESC;

--Which vehicle models generated the highest total revenue?
--Return: make, model, total_revenue

SELECT
    v.make,
    v.model,
    COUNT(*) AS total_vehicles_sold,
    ROUND(SUM(a.selling_price), 2) AS total_revenue
FROM vehicles v
JOIN auction_sales a
    ON v.vehicle_id = a.vehicle_id
WHERE v.make IS NOT NULL
  AND v.model IS NOT NULL
GROUP BY v.make, v.model
ORDER BY total_revenue DESC;

--Which vehicle makes contribute the most revenue to the business, 
--and what percentage of total revenue does each make contribute?

WITH vehicle_revenue AS (
    SELECT
        v.make,
        SUM(a.selling_price) AS total_revenue
    FROM vehicles v
    JOIN auction_sales a
        ON v.vehicle_id = a.vehicle_id
    GROUP BY v.make
)

SELECT
    make,
    total_revenue,
    ROUND(
        (total_revenue * 100) /
        (SUM(total_revenue) OVER()),
        2
    ) AS revenue_percentage
FROM vehicle_revenue
ORDER BY total_revenue DESC;

--Which vehicle makes are performing above average revenue, 
--and which are performing below average revenue?

WITH vehicle_revenue AS (
    SELECT
        v.make,
        SUM(a.selling_price) AS total_revenue
    FROM vehicles v
    JOIN auction_sales a
        ON v.vehicle_id = a.vehicle_id
    GROUP BY v.make
)

SELECT
    make,
    total_revenue,
    CASE
        WHEN total_revenue >
             AVG(total_revenue) OVER()
             THEN 'ABOVE_AVERAGE'
        ELSE 'BELOW_AVERAGE'
    END AS performance
FROM vehicle_revenue
ORDER BY total_revenue DESC;

--Find the Top 5 vehicle makes by total revenue.
--Return:rank, make, total_revenue

WITH vehicle_revenue AS (
    SELECT
        v.make,
        SUM(a.selling_price) AS total_revenue,
        COUNT(*) AS total_sold_vehicles
    FROM vehicles v
    JOIN auction_sales a
        ON v.vehicle_id = a.vehicle_id
    GROUP BY v.make
),
ranked_revenue AS (
    SELECT
        make,
        total_revenue,
        total_sold_vehicles,
        DENSE_RANK() OVER (
            ORDER BY total_revenue DESC
        ) AS revenue_rank
    FROM vehicle_revenue
)

SELECT *
FROM ranked_revenue
WHERE revenue_rank <= 5
ORDER BY revenue_rank;

--Which vehicle makes generated more revenue 
--than the average revenue of all vehicle makes?

WITH vehicle_revenue AS (
    SELECT
        v.make,
        SUM(a.selling_price) AS total_revenue
    FROM vehicles v
    JOIN auction_sales a
        ON v.vehicle_id = a.vehicle_id
    GROUP BY v.make
)

SELECT
    make,
    total_revenue
FROM vehicle_revenue
WHERE total_revenue >
(
    SELECT AVG(total_revenue)
    FROM vehicle_revenue
)
ORDER BY total_revenue DESC;

--Which vehicle makes have sold more vehicles than the 
--average number of vehicles sold across all makes?

WITH vechiles_sale_count AS (
    SELECT
        v.make,
        COUNT(*) AS total_count
    FROM vehicles v
    JOIN auction_sales a
        ON v.vehicle_id = a.vehicle_id
    GROUP BY v.make
)

SELECT make, total_count
FROM vechiles_sale_count
WHERE total_count >
(
    SELECT AVG(total_count)
    FROM vechiles_sale_count
)
ORDER BY total_count DESC;

--For each vehicle make, show the model that sold the most vehicles.

WITH total_vehicle AS (
    SELECT
        v.make,
        v.model,
        COUNT(*) AS total_count
    FROM vehicles v
    JOIN auction_sales a
        ON v.vehicle_id = a.vehicle_id
    GROUP BY v.make, v.model
),

model_ranking AS (
    SELECT
        make,
        model,
        total_count,
        RANK() OVER (
            PARTITION BY make
            ORDER BY total_count DESC
        ) AS rn
    FROM total_vehicle
)

SELECT *
FROM model_ranking
WHERE rn = 1;

--For each vehicle make, show the top 3 models by total revenue.

WITH vehicle_revenue AS (
    SELECT
        v.make,
        v.model,
        SUM(a.selling_price) AS total_revenue
    FROM vehicles v
    JOIN auction_sales a
        ON v.vehicle_id = a.vehicle_id
    GROUP BY v.make, v.model
),

model_ranking AS (
    SELECT
        make,
        model,
        total_revenue,
        RANK() OVER (
            PARTITION BY make
            ORDER BY total_revenue DESC
        ) AS rn
    FROM vehicle_revenue
)

SELECT *
FROM model_ranking
WHERE rn <= 3
ORDER BY make, rn;

--Which vehicle makes have a higher average selling price than 
--the overall average selling price across all vehicles?

WITH average_selling_price AS (
    SELECT
        v.make,
        ROUND(AVG(a.selling_price),2) AS average_price
    FROM vehicles v
    JOIN auction_sales a
        ON v.vehicle_id = a.vehicle_id
    GROUP BY v.make
)

SELECT
    make,
    average_price
FROM average_selling_price
WHERE average_price >
(
    SELECT AVG(selling_price)
    FROM auction_sales
)
ORDER BY average_price DESC;

--Which vehicle makes consistently sell above their market 
--value (MMR), and by what percentage?
--Expected columns: make, average_mmr, average_selling_price,premium_percentage

WITH vehicles_makes AS (
    SELECT
        v.make,
        ROUND(AVG(a.mmr),2) AS average_mmr,
        ROUND(AVG(a.selling_price),2) AS average_selling_price
    FROM vehicles v
    JOIN auction_sales a
        ON v.vehicle_id = a.vehicle_id
    GROUP BY v.make
),
premium_vehicle AS (
    SELECT
        make,
        average_mmr,
        average_selling_price,
        ROUND(
            ((average_selling_price-average_mmr)*100/nullif(average_mmr, 0)),
            2
        ) AS premium_percentage
    FROM vehicles_makes
)
SELECT
    make,
    average_mmr,
    average_selling_price,
    premium_percentage
FROM premium_vehicle
WHERE premium_percentage > 0
ORDER BY premium_percentage DESC;

--Which vehicle makes generate a large percentage of company revenue?

WITH vechiles_revenue AS (
    SELECT
        v.make,
        SUM(a.selling_price) AS total_revenue
    FROM vehicles v
    JOIN auction_sales a
        ON v.vehicle_id = a.vehicle_id
    GROUP BY v.make
),

revenue_percentages AS (
    SELECT
        make,
        total_revenue,
        ROUND(
            (total_revenue * 100) /
            SUM(total_revenue) OVER()
        ,2) AS revenue_percentage
    FROM vechiles_revenue
)

SELECT
    make,
    total_revenue,
    revenue_percentage,
    SUM(revenue_percentage)
        OVER(ORDER BY total_revenue DESC
        Rows UNBOUNDED PRECEDING)
        AS cummulative_percentage
FROM revenue_percentages;


--Which vehicle makes have high revenue but low sales volume?
--Return: make, total_count, total_revenue, average_selling_price


with vehicle_analysis AS (
    SELECT
        v.make,
        COUNT(*) AS total_count,
        SUM(a.selling_price) AS total_revenue,
        ROUND(AVG(a.selling_price),2) AS average_selling_price
    FROM vehicles v
    JOIN auction_sales a
        ON v.vehicle_id = a.vehicle_id
    GROUP BY v.make
)

SELECT *
FROM vehicle_analysis
WHERE total_count < (
    SELECT AVG(total_count)
    FROM vehicle_analysis
)
AND total_revenue > (
    SELECT AVG(total_revenue)
    FROM vehicle_analysis
)
ORDER BY total_revenue DESC;

--Which vehicle makes have high sales volume 
--but below-average selling prices?
--Return: make, total_count, total_revenue, average_selling_price

WITH vehicle_analysis AS (
    SELECT
        v.make,
        COUNT(*) AS total_count,
        SUM(a.selling_price) AS total_revenue,
        ROUND(AVG(a.selling_price),2) AS average_selling_price
    FROM vehicles v
    JOIN auction_sales a
        ON v.vehicle_id = a.vehicle_id
    GROUP BY v.make
)

SELECT *
FROM vehicle_analysis
WHERE total_count > (
    SELECT AVG(total_count)
    FROM vehicle_analysis
)
AND average_selling_price < (
    SELECT AVG(average_selling_price)
    FROM vehicle_analysis
)
ORDER BY total_revenue DESC;

--Identify brands where pricing, upselling, 
--or inventory strategy could potentially increase revenue.
--Which vehicle makes are “hidden opportunities”?
--Return: make, total_count, total_revenue, average_selling_price

WITH vehicle_analysis AS (
    SELECT
        v.make,
        COUNT(*) AS total_count,
        SUM(a.selling_price) AS total_revenue,
        ROUND(AVG(a.selling_price),2) AS average_selling_price
    FROM vehicles v
    JOIN auction_sales a
        ON v.vehicle_id = a.vehicle_id
    GROUP BY v.make
)

SELECT *
FROM vehicle_analysis
WHERE total_count > (
    SELECT AVG(total_count)
    FROM vehicle_analysis
)
AND total_revenue < (
    SELECT AVG(total_revenue)
    FROM vehicle_analysis
)
ORDER BY total_revenue DESC;

--Which vehicle makes generate the highest revenue per vehicle sold?
--Return: make, total_count, total_revenue revenue_per_vehicle

WITH vehicle_analysis AS (
    SELECT
        v.make,
        COUNT(*) AS total_count,
        SUM(a.selling_price) AS total_revenue
    FROM vehicles v
    JOIN auction_sales a
        ON v.vehicle_id = a.vehicle_id
    GROUP BY v.make
)

SELECT
    make,
    total_count,
    total_revenue,
    ROUND(total_revenue / total_count, 2) AS revenue_per_vehicle
FROM vehicle_analysis
WHERE total_count >= 10
ORDER BY revenue_per_vehicle DESC;
